name: Test, Build, Publish

on:
  push:
    tags:
      - "*"

jobs:
  publish-npm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 18
          registry-url: https://registry.npmjs.org/
      - run: cp ./README.md ./package/README.md
      - run: cd ./package && npm ci
      - run: cd ./package && npm run build
      - run: cd ./package && npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.npm_token}}
